# Generated by Django 5.2.7 on 2025-11-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='iamge',
            new_name='image',
        ),
    ]
